package io.openems.edge.victron.ess;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.common.type.Phase.SingleOrAllPhase;

@ObjectClassDefinition(//
		name = "Victron Multiplus 2 ESS", //
		description = "Victron ESS system with Multiplus2 inverter - ESS")
public @interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 227;

	@AttributeDefinition(name = "Connected Phase", description = "to which phase is the ESS connected?")
	SingleOrAllPhase phase() default SingleOrAllPhase.ALL;

	@AttributeDefinition(name = "Debug", description = "Enable debug mode?")
	boolean debugMode() default false;

	@AttributeDefinition(name = "Read-Only mode", description = "Enables Read-Only mode")
	boolean readOnlyMode() default false;

	@AttributeDefinition(name = "Capacity", description = "Total battery capacity in Wh")
	int capacity() default 10000;

	@AttributeDefinition(name = "Max Apparent Power", description = "Maximum apparent power in VA")
	int maxApparentPower() default 5000;

	@AttributeDefinition(name = "Manage DC overvoltage feed-in", //
			description = "If enabled, OpenEMS writes the DC-coupled PV overvoltage feed-in registers (65-68, 71, 72) "
					+ "from the settings below. Overvoltage feed-in exports surplus PV independently of the battery AC "
					+ "power setpoint, so it does NOT count against the discharge limit. Leave disabled to keep the "
					+ "GX/VRM 'Feed-in excess solar charger power' settings authoritative.")
	boolean manageOvervoltageFeedIn() default false;

	@AttributeDefinition(name = "Feed DC overvoltage into grid", //
			description = "Allow DC-coupled PV surplus to be fed into the grid via overvoltage feed-in (register 65). "
					+ "Only used when 'Manage DC overvoltage feed-in' is enabled.")
	boolean feedDcOvervoltageToGrid() default false;

	@AttributeDefinition(name = "Max feed-in power [W]", //
			description = "Maximum total grid feed-in power in Watts, split evenly across the connected phases "
					+ "(registers 66-68). Use -1 for unlimited. Only used when 'Manage DC overvoltage feed-in' is enabled.")
	int maxFeedInPowerW() default -1;

	@AttributeDefinition(name = "Fine solar offset (0.1V)", //
			description = "Use the finer 0.1 V overvoltage feed-in offset instead of the default 1 V (register 72). "
					+ "Recommended for ESS mode 3 external control. Only used when 'Manage DC overvoltage feed-in' is enabled.")
	boolean fixSolarOffsetTo100mV() default false;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Victron Multiplus 2 ESS [{id}]";

}